[workspace]
members = ["crates/mdl-cli", "crates/mdl-compiler", "crates/mdl-test", "crates/mcfunction-executor"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.85"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
