module main

import os

// Codegen - Generates .mcfunction files from IR
//
// === Storage Layout ===
// Data variables (storage):
//   - Function args:   storage <mc_ns>:<mdl_ns> <func>.$args.<argname>
//   - Function result: storage <mc_ns>:<mdl_ns> <func>.$result
//   - Data variables:  storage <mc_ns>:<mdl_ns> <func>.<varname>
//
// Register variables (scoreboard) - integers only:
//   - Objective: <project_name>
//   - Player: <mdl_ns>_<func>_<varname>
//
// === File Structure ===
// Super nested structure:
//   ns/func.mcfunction          - Entry point (calls entry block)
//   ns/func/entry_0.mcfunction  - Entry basic block
//   ns/func/if_then_1.mcfunction - Then branch
//   ns/func/if_else_2.mcfunction - Else branch
//   etc.
//
// === Macro Passing ===
// Basic blocks that need macro values are called with:
//   function <ns>:<path> with storage <ns>:<mdl_ns> <func>.$macro_args
// or with immediate dict:
//   function <ns>:<path> with {key: value, ...}
// Inside the function, $(key) expands to the value.
//
// Reference macros (&var) are inserted raw, non-ref macros use $().

pub struct Codegen {
pub mut:
	builder      &IRBuilder
	output_dir   string
	project_name string  // Scoreboard objective name
}

pub fn Codegen.new(builder &IRBuilder, output_dir string, project_name string) Codegen {
	return Codegen{
		builder:      builder
		output_dir:   output_dir
		project_name: project_name
	}
}

// Generate all mcfunction files
pub fn (mut c Codegen) generate() ! {
	// Create base output directory
	os.mkdir_all(c.output_dir) or {
		return error('Could not create output directory: ${c.output_dir}')
	}

	// Create pack.mcmeta
	c.write_pack_mcmeta()!

	// Generate init function for scoreboards
	c.generate_init_function()!

	// Generate functions for each namespace
	for ns in c.builder.namespaces {
		c.generate_namespace(ns)!
	}
}

// Write pack.mcmeta file
fn (mut c Codegen) write_pack_mcmeta() ! {
	mcmeta := '{
  "pack": {
    "pack_format": 48,
    "description": "Generated by MDL compiler"
  }
}'
	os.write_file(os.join_path(c.output_dir, 'pack.mcmeta'), mcmeta)!
}

// Generate init function that creates scoreboards
fn (mut c Codegen) generate_init_function() ! {
	// Init function goes in output/data/<project_name>/function/
	init_path := os.join_path(c.output_dir, 'data', c.project_name, 'function')
	os.mkdir_all(init_path)!

	mut lines := []string{}
	lines << '# Initialize scoreboards for ${c.project_name}'
	lines << 'scoreboard objectives add ${c.project_name} dummy'

	os.write_file(os.join_path(init_path, 'init.mcfunction'), lines.join('\n'))!
}

// Generate mcfunction files for a namespace
pub fn (mut c Codegen) generate_namespace(ns IRNamespace) ! {
	// Base path: output/data/<project_name>/function/<namespace>/
	ns_parts := c.get_ns_parts(ns)
	ns_path := os.join_path(c.output_dir, 'data', c.project_name, 'function', ns_parts.join('/'))
	os.mkdir_all(ns_path)!

	for fid in ns.functions {
		c.generate_function(fid, ns, ns_path)!
	}
}

// Generate mcfunction files for a function
pub fn (mut c Codegen) generate_function(fid FID, ns IRNamespace, ns_path string) ! {
	func := c.builder.functions[fid]

	// Create function subdirectory for basic blocks
	func_dir := os.join_path(ns_path, func.name)
	os.mkdir_all(func_dir)!

	// Generate entry point: ns/func.mcfunction
	// This sets up args and calls the entry block
	c.generate_function_entry(fid, ns, ns_path)!

	// Generate each basic block: ns/func/block_id.mcfunction
	for bbid in func.bbs {
		c.generate_basic_block(bbid, ns, func_dir)!
	}
}

// Generate function entry point that calls the entry block
fn (mut c Codegen) generate_function_entry(fid FID, ns IRNamespace, fs_path string) ! {
	func := c.builder.functions[fid]
	mut lines := []string{}

	ns_parts := c.get_ns_parts(ns)
	lines << '# Entry point for ${ns_parts.join(".")}.${func.name}'

	// Call the entry basic block
	entry_bb := c.builder.basic_blocks[func.entrybb]
	bb_func_path := c.build_func_path(ns, func.name, '${entry_bb.label}_${entry_bb.id}')

	if entry_bb.args.len > 0 {
		// Need to pass macro arguments
		args_storage := c.build_storage_path(ns, func.name, '\$args')
		lines << 'function ${bb_func_path} with storage ${args_storage}'
	} else {
		lines << 'function ${bb_func_path}'
	}

	filepath := os.join_path(fs_path, '${func.name}.mcfunction')
	os.write_file(filepath, lines.join('\n'))!
}

// Generate a single .mcfunction file for a basic block
pub fn (mut c Codegen) generate_basic_block(bbid BBID, ns IRNamespace, func_dir string) ! {
	bb := c.builder.basic_blocks[bbid]

	filename := '${bb.label}_${bb.id}.mcfunction'
	filepath := os.join_path(func_dir, filename)

	mut lines := []string{}
	lines << '# Basic block: ${bb.label} (id: ${bb.id})'

	// Generate commands for each instruction
	for iid in bb.insts {
		inst_lines := c.generate_instruction(bb.function, bbid, iid, ns)
		lines << inst_lines
	}

	os.write_file(filepath, lines.join('\n'))!
}

// Generate mcfunction commands for a single instruction
pub fn (mut c Codegen) generate_instruction(fid FID, bbid BBID, iid IID, ns IRNamespace) []string {
	func := c.builder.functions[fid]
	inst := func.insts[iid]

	mut lines := []string{}

	match inst {
		IRDefine {
			lines << c.gen_define(fid, bbid, inst, ns)
		}
		IRTypedDefine {
			lines << c.gen_typed_define(fid, bbid, inst, ns)
		}
		IRAssign {
			lines << c.gen_assign(fid, bbid, inst, ns)
		}
		IRStore {
			lines << c.gen_store(fid, bbid, inst, ns)
		}
		IRBinaryOp {
			lines << c.gen_binary_op(fid, bbid, inst, ns)
		}
		IRUnaryOp {
			lines << c.gen_unary_op(fid, bbid, inst, ns)
		}
		IRCall {
			lines << c.gen_call(fid, bbid, inst, ns)
		}
		IRJump {
			lines << c.gen_jump(fid, bbid, inst, ns)
		}
		IRBranch {
			lines << c.gen_branch(fid, bbid, inst, ns)
		}
		IRReturn {
			lines << c.gen_return(fid, bbid, inst, ns)
		}
		IRMacroLiteralCmd {
			lines << c.gen_macro_cmd(fid, bbid, inst, ns)
		}
		IRFieldAccess {
			lines << c.gen_field_access(fid, bbid, inst, ns)
		}
		IRIndexAccess {
			lines << c.gen_index_access(fid, bbid, inst, ns)
		}
		IRDeref {
			lines << c.gen_deref(fid, bbid, inst, ns)
		}
		IRRefInst {
			lines << c.gen_ref(fid, bbid, inst, ns)
		}
		IRStructInit {
			lines << c.gen_struct_init(fid, bbid, inst, ns)
		}
	}

	return lines
}

// ==================== Instruction Generators ====================

fn (mut c Codegen) gen_define(fid FID, bbid BBID, inst IRDefine, ns IRNamespace) []string {
	mut lines := []string{}

	// Get storage kinds for dest and source
	dest_kind := c.get_ref_storage(fid, inst.result)
	src_kind := c.get_oid_storage(fid, inst.value)

	match dest_kind {
		.register {
			dest_player := c.scoreboard_player(fid, inst.result)
			match src_kind {
				.register {
					// register <- register: use operation =
					src_player := c.oid_to_score_player(fid, bbid, inst.value, ns)
					lines << 'scoreboard players operation ${dest_player} ${c.project_name} = ${src_player} ${c.project_name}'
				}
				.data {
					// register <- data: execute store result score ... run data get
					src_path := c.oid_to_storage_path(fid, inst.value, ns)
					lines << 'execute store result score ${dest_player} ${c.project_name} run data get storage ${src_path}'
				}
				.effemeral {
					// register <- constant: scoreboard players set
					value_cmd := c.oid_to_value_cmd(fid, bbid, inst.value, ns)
					lines << 'scoreboard players set ${dest_player} ${c.project_name} ${value_cmd}'
				}
			}
		}
		.data {
			dest_path := c.storage_path_rid(fid, inst.result, ns)
			match src_kind {
				.register {
					// data <- register: execute store result storage ... run scoreboard players get
					src_player := c.oid_to_score_player(fid, bbid, inst.value, ns)
					lines << 'execute store result storage ${dest_path} int 1 run scoreboard players get ${src_player} ${c.project_name}'
				}
				.data {
					// data <- data: data modify ... set from storage
					value_cmd := c.oid_to_storage_cmd(fid, bbid, inst.value, ns)
					lines << 'data modify storage ${dest_path} set ${value_cmd}'
				}
				.effemeral {
					// data <- constant: data modify ... set value
					value_cmd := c.oid_to_storage_cmd(fid, bbid, inst.value, ns)
					lines << 'data modify storage ${dest_path} set ${value_cmd}'
				}
			}
		}
		.effemeral {
			lines << '# ephemeral define (no storage)'
		}
	}

	return lines
}

fn (mut c Codegen) gen_typed_define(fid FID, bbid BBID, inst IRTypedDefine, ns IRNamespace) []string {
	// Typed define just declares, doesn't initialize
	return ['# typed define (declaration only)']
}

fn (mut c Codegen) gen_assign(fid FID, bbid BBID, inst IRAssign, ns IRNamespace) []string {
	mut lines := []string{}

	dest_kind := c.get_ref_storage(fid, inst.result)
	src_kind := c.get_oid_storage(fid, inst.value)

	match dest_kind {
		.register {
			dest_player := c.scoreboard_player(fid, inst.result)
			match inst.op {
				.assign {
					// Handle storage kind conversion for simple assignment
					match src_kind {
						.register {
							src_player := c.oid_to_score_player(fid, bbid, inst.value, ns)
							lines << 'scoreboard players operation ${dest_player} ${c.project_name} = ${src_player} ${c.project_name}'
						}
						.data {
							src_path := c.oid_to_storage_path(fid, inst.value, ns)
							lines << 'execute store result score ${dest_player} ${c.project_name} run data get storage ${src_path}'
						}
						.effemeral {
							value_cmd := c.oid_to_value_cmd(fid, bbid, inst.value, ns)
							lines << 'scoreboard players set ${dest_player} ${c.project_name} ${value_cmd}'
						}
					}
				}
				.add_assign {
					value_cmd := c.oid_to_value_cmd(fid, bbid, inst.value, ns)
					lines << 'scoreboard players add ${dest_player} ${c.project_name} ${value_cmd}'
				}
				.sub_assign {
					value_cmd := c.oid_to_value_cmd(fid, bbid, inst.value, ns)
					lines << 'scoreboard players remove ${dest_player} ${c.project_name} ${value_cmd}'
				}
				.mul_assign, .div_assign, .mod_assign {
					other := c.oid_to_score_player(fid, bbid, inst.value, ns)
					op_str := match inst.op {
						.mul_assign { '*=' }
						.div_assign { '/=' }
						.mod_assign { '%=' }
						else { '=' }
					}
					lines << 'scoreboard players operation ${dest_player} ${c.project_name} ${op_str} ${other} ${c.project_name}'
				}
				.swap {
					other := c.oid_to_score_player(fid, bbid, inst.value, ns)
					lines << 'scoreboard players operation ${dest_player} ${c.project_name} >< ${other} ${c.project_name}'
				}
			}
		}
		.data {
			dest_path := c.storage_path_rid(fid, inst.result, ns)
			match inst.op {
				.assign {
					// Handle storage kind conversion for simple assignment
					match src_kind {
						.register {
							src_player := c.oid_to_score_player(fid, bbid, inst.value, ns)
							lines << 'execute store result storage ${dest_path} int 1 run scoreboard players get ${src_player} ${c.project_name}'
						}
						.data, .effemeral {
							value_cmd := c.oid_to_storage_cmd(fid, bbid, inst.value, ns)
							lines << 'data modify storage ${dest_path} set ${value_cmd}'
						}
					}
				}
				else {
					// Compound assignments on data require loading to scoreboard first
					// This should ideally be handled by an IR pass
					lines << '# TODO: compound assignment on data storage requires scoreboard temp'
				}
			}
		}
		.effemeral {
			lines << '# ephemeral assign'
		}
	}

	return lines
}

fn (mut c Codegen) gen_store(fid FID, bbid BBID, inst IRStore, ns IRNamespace) []string {
	// Store copies from source to result (both are RIDs)
	mut lines := []string{}
	dest_path := c.storage_path_rid(fid, inst.result, ns)
	src_path := c.storage_path_rid(fid, inst.source, ns)
	lines << 'data modify storage ${dest_path} set from storage ${src_path}'
	return lines
}

fn (mut c Codegen) gen_binary_op(fid FID, bbid BBID, inst IRBinaryOp, ns IRNamespace) []string {
	mut lines := []string{}
	func := c.builder.functions[fid]

	// Binary ops on integers use scoreboard operations
	result_player := c.scoreboard_player(fid, inst.result)

	// Get storage kinds for operands
	left_kind := c.get_oid_storage(fid, inst.left)
	right_kind := c.get_oid_storage(fid, inst.right)

	// Handle left operand - load into scoreboard if needed
	left_player := c.oid_to_score_player(fid, bbid, inst.left, ns)
	match left_kind {
		.data {
			// Load from storage into scoreboard
			left_path := c.oid_to_storage_path(fid, inst.left, ns)
			lines << 'execute store result score ${left_player} ${c.project_name} run data get storage ${left_path}'
		}
		.effemeral {
			// Constant - set directly
			if inst.left is CID {
				cnst := func.consts[inst.left]
				if cnst is IRIntConst {
					lines << 'scoreboard players set ${left_player} ${c.project_name} ${cnst.value}'
				}
			}
		}
		.register {
			// Already in scoreboard, nothing to do
		}
	}

	// Handle right operand - load into scoreboard if needed
	right_player := c.oid_to_score_player(fid, bbid, inst.right, ns)
	match right_kind {
		.data {
			// Load from storage into scoreboard
			right_path := c.oid_to_storage_path(fid, inst.right, ns)
			lines << 'execute store result score ${right_player} ${c.project_name} run data get storage ${right_path}'
		}
		.effemeral {
			// Constant - set directly
			if inst.right is CID {
				cnst := func.consts[inst.right]
				if cnst is IRIntConst {
					lines << 'scoreboard players set ${right_player} ${c.project_name} ${cnst.value}'
				}
			}
		}
		.register {
			// Already in scoreboard, nothing to do
		}
	}

	// First, copy left to result
	lines << 'scoreboard players operation ${result_player} ${c.project_name} = ${left_player} ${c.project_name}'

	// Then apply operation with right
	op_str := match inst.op {
		.add { '+=' }
		.sub { '-=' }
		.mul { '*=' }
		.div { '/=' }
		.mod { '%=' }
		.lt { '<' }
		.le { '<=' }
		.gt { '>' }
		.ge { '>=' }
		.eq { '=' }
		.ne { '=' }  // Will need special handling
	}

	match inst.op {
		.add, .sub, .mul, .div, .mod {
			lines << 'scoreboard players operation ${result_player} ${c.project_name} ${op_str} ${right_player} ${c.project_name}'
		}
		.lt, .le, .gt, .ge, .eq, .ne {
			// Comparison - set result to 1 if true, 0 if false
			lines << 'scoreboard players set ${result_player} ${c.project_name} 0'
			cmp_op := match inst.op {
				.lt { '<' }
				.le { '<=' }
				.gt { '>' }
				.ge { '>=' }
				.eq { '=' }
				.ne { '=' }
				else { '=' }
			}
			if inst.op == .ne {
				lines << 'execute unless score ${left_player} ${c.project_name} = ${right_player} ${c.project_name} run scoreboard players set ${result_player} ${c.project_name} 1'
			} else {
				lines << 'execute if score ${left_player} ${c.project_name} ${cmp_op} ${right_player} ${c.project_name} run scoreboard players set ${result_player} ${c.project_name} 1'
			}
		}
	}

	return lines
}

fn (mut c Codegen) gen_unary_op(fid FID, bbid BBID, inst IRUnaryOp, ns IRNamespace) []string {
	mut lines := []string{}

	result_player := c.scoreboard_player(fid, inst.result)
	operand_player := c.oid_to_score_player(fid, bbid, inst.operand, ns)

	match inst.op {
		.neg {
			// Negate: result = 0 - operand
			lines << 'scoreboard players set ${result_player} ${c.project_name} 0'
			lines << 'scoreboard players operation ${result_player} ${c.project_name} -= ${operand_player} ${c.project_name}'
		}
		else {
			lines << '# unary op not applicable for scoreboard'
		}
	}

	return lines
}

fn (mut c Codegen) gen_call(fid FID, bbid BBID, inst IRCall, ns IRNamespace) []string {
	mut lines := []string{}

	called_func := c.builder.functions[inst.function]
	called_ns := c.builder.namespaces[called_func.namespace]

	func_path := c.build_func_path(called_ns, called_func.name)

	if inst.args.len == 0 {
		// No arguments
		lines << 'function ${func_path}'
	} else {
		// Check if all args are constants (can inline)
		mut all_constants := true
		for arg_oid in inst.args {
			if arg_oid is RID {
				all_constants = false
				break
			}
		}

		if all_constants {
			// All constants - use inline dict (no 'with' keyword)
			mut dict_parts := []string{}
			for i, arg_oid in inst.args {
				arg_def := called_func.args[i]
				value := c.oid_to_nbt_value(fid, bbid, arg_oid, ns)
				dict_parts << '${arg_def.name}: ${value}'
			}
			lines << 'function ${func_path} {${dict_parts.join(", ")}}'
		} else {
			// Has variables - need to copy to storage first, then call with storage
			args_storage := c.build_storage_path(called_ns, called_func.name, '\$args')

			for i, arg_oid in inst.args {
				arg_def := called_func.args[i]
				arg_path := '${args_storage}.${arg_def.name}'

				match arg_oid {
					CID {
						// Constant - set value directly
						value_cmd := c.oid_to_storage_cmd(fid, bbid, arg_oid, ns)
						lines << 'data modify storage ${arg_path} set ${value_cmd}'
					}
					RID {
						// Variable - check if register or data
						storage_kind := c.get_ref_storage(fid, arg_oid)
						match storage_kind {
							.register {
								// Register: execute store result storage ... run scoreboard players get
								player := c.scoreboard_player(fid, arg_oid)
								lines << 'execute store result storage ${arg_path} int 1 run scoreboard players get ${player} ${c.project_name}'
							}
							.data {
								// Data: data modify storage ... set from storage
								src_path := c.storage_path_rid(fid, arg_oid, ns)
								lines << 'data modify storage ${arg_path} set from storage ${src_path}'
							}
							.effemeral {
								// Ephemeral - shouldn't happen for RID
								lines << '# ephemeral arg (unexpected)'
							}
						}
					}
				}
			}

			lines << 'function ${func_path} with storage ${args_storage}'
		}
	}

	// Copy result if needed
	if result_rid := inst.result {
		result_path := c.storage_path_rid(fid, result_rid, ns)
		called_result := c.build_storage_path(called_ns, called_func.name, '\$result')
		lines << 'data modify storage ${result_path} set from storage ${called_result}'
	}

	return lines
}

// Check if an OID can be inlined directly (constants only, not variables)
fn (mut c Codegen) can_inline_oid(fid FID, oid OID) bool {
	func := c.builder.functions[fid]
	match oid {
		CID {
			cnst := func.consts[oid]
			// Can inline simple constants
			return cnst is IRIntConst || cnst is IRFloatConst ||
			       cnst is IRCharConst || cnst is IRStringConst
		}
		RID {
			// RIDs are variables - cannot inline, need storage
			return false
		}
	}
}

fn (mut c Codegen) gen_jump(fid FID, bbid BBID, inst IRJump, ns IRNamespace) []string {
	mut lines := []string{}

	func := c.builder.functions[fid]
	target_bb := c.builder.basic_blocks[inst.target]
	target_path := c.build_func_path(ns, func.name, '${target_bb.label}_${target_bb.id}')

	if inst.args.len == 0 {
		lines << 'function ${target_path}'
		return lines
	}

	// Check if all args are constants (can inline)
	mut all_constants := true
	for arg_oid in inst.args {
		if arg_oid is RID {
			all_constants = false
			break
		}
	}

	if all_constants {
		// All constants - use inline dict (no 'with' keyword)
		mut dict_parts := []string{}
		for i, arg_oid in inst.args {
			arg_name := target_bb.args[i].name
			value := c.oid_to_nbt_value(fid, bbid, arg_oid, ns)
			dict_parts << '${arg_name}: ${value}'
		}
		lines << 'function ${target_path} {${dict_parts.join(", ")}}'
	} else {
		// Has variables - need to copy to storage first, then call with storage
		target_name := '${target_bb.label}_${target_bb.id}'
		args_storage := c.build_storage_path(ns, func.name, '\$${target_name}', '\$args')

		for i, arg_oid in inst.args {
			arg_name := target_bb.args[i].name
			arg_path := '${args_storage}.${arg_name}'

			match arg_oid {
				CID {
					// Constant - set value directly
					value_cmd := c.oid_to_storage_cmd(fid, bbid, arg_oid, ns)
					lines << 'data modify storage ${arg_path} set ${value_cmd}'
				}
				RID {
					// Variable - check if register or data
					storage_kind := c.get_ref_storage(fid, arg_oid)
					match storage_kind {
						.register {
							// Register: execute store result storage ... run scoreboard players get
							player := c.scoreboard_player(fid, arg_oid)
							lines << 'execute store result storage ${arg_path} int 1 run scoreboard players get ${player} ${c.project_name}'
						}
						.data {
							// Data: data modify storage ... set from storage
							src_path := c.storage_path_rid(fid, arg_oid, ns)
							lines << 'data modify storage ${arg_path} set from storage ${src_path}'
						}
						.effemeral {
							// Ephemeral - shouldn't happen for RID
							lines << '# ephemeral arg (unexpected)'
						}
					}
				}
			}
		}

		lines << 'function ${target_path} with storage ${args_storage}'
	}

	return lines
}

fn (mut c Codegen) gen_branch(fid FID, bbid BBID, inst IRBranch, ns IRNamespace) []string {
	mut lines := []string{}

	func := c.builder.functions[fid]
	then_bb := c.builder.basic_blocks[inst.then_bb]
	else_bb := c.builder.basic_blocks[inst.else_bb]

	then_path := c.build_func_path(ns, func.name, '${then_bb.label}_${then_bb.id}')
	else_path := c.build_func_path(ns, func.name, '${else_bb.label}_${else_bb.id}')

	// Condition is a score (1 = true, 0 = false)
	cond_player := c.oid_to_score_player(fid, bbid, inst.cond, ns)

	// Branch based on condition
	lines << 'execute if score ${cond_player} ${c.project_name} matches 1.. run function ${then_path}'
	lines << 'execute if score ${cond_player} ${c.project_name} matches ..0 run function ${else_path}'

	return lines
}

fn (mut c Codegen) gen_return(fid FID, bbid BBID, inst IRReturn, ns IRNamespace) []string {
	mut lines := []string{}

	func := c.builder.functions[fid]

	if value := inst.value {
		// Copy return value to $result (which is always storage)
		result_path := c.build_storage_path(ns, func.name, '\$result')
		src_kind := c.get_oid_storage(fid, value)

		match src_kind {
			.register {
				// register -> storage: use execute store
				src_player := c.oid_to_score_player(fid, bbid, value, ns)
				lines << 'execute store result storage ${result_path} int 1 run scoreboard players get ${src_player} ${c.project_name}'
			}
			.data, .effemeral {
				// data/constant -> storage: use data modify
				value_cmd := c.oid_to_storage_cmd(fid, bbid, value, ns)
				lines << 'data modify storage ${result_path} set ${value_cmd}'
			}
		}
	}

	// Return is implicit (end of mcfunction)
	lines << '# return'

	return lines
}

fn (mut c Codegen) gen_macro_cmd(fid FID, bbid BBID, inst IRMacroLiteralCmd, ns IRNamespace) []string {
	mut lines := []string{}

	// Build the command string with macro substitutions
	mut cmd := '\$'  // Start with $ for mcfunction macro command

	for part in inst.parts {
		match part {
			IRMacroCmdText {
				cmd += part.text
			}
			IRMacroCmdMacro {
				// Both ref and non-ref use $() substitution for macro commands
				// The is_ref flag affects how the value is passed, not the syntax
				name := c.get_ref_name(fid, part.value)
				cmd += '\$(${name})'
			}
			IRMacroCmdString {
				for str_part in part.parts {
					match str_part {
						IRStringText {
							cmd += str_part.text
						}
						IRStringMacro {
							// Both ref and non-ref use $() substitution
							name := c.get_ref_name(fid, str_part.value)
							cmd += '\$(${name})'
						}
					}
				}
			}
		}
	}

	lines << cmd
	return lines
}

fn (mut c Codegen) gen_field_access(fid FID, bbid BBID, inst IRFieldAccess, ns IRNamespace) []string {
	mut lines := []string{}
	src_path := c.storage_path_rid(fid, inst.source, ns)
	dest_path := c.storage_path_rid(fid, inst.result, ns)
	lines << 'data modify storage ${dest_path} set from storage ${src_path}.${inst.field}'
	return lines
}

fn (mut c Codegen) gen_index_access(fid FID, bbid BBID, inst IRIndexAccess, ns IRNamespace) []string {
	mut lines := []string{}
	src_path := c.storage_path_rid(fid, inst.source, ns)
	dest_path := c.storage_path_rid(fid, inst.result, ns)

	// Index can be constant or variable
	index_str := c.oid_to_index_str(fid, bbid, inst.index, ns)
	lines << 'data modify storage ${dest_path} set from storage ${src_path}[${index_str}]'
	return lines
}

fn (mut c Codegen) gen_deref(fid FID, bbid BBID, inst IRDeref, ns IRNamespace) []string {
	mut lines := []string{}
	// Dereference - the source contains a path, copy from that path
	src_path := c.storage_path_rid(fid, inst.source, ns)
	dest_path := c.storage_path_rid(fid, inst.result, ns)
	// This requires indirect access - use macro
	lines << '# deref - indirect storage access'
	lines << 'data modify storage ${dest_path} set from storage ${src_path}'
	return lines
}

fn (mut c Codegen) gen_ref(fid FID, bbid BBID, inst IRRefInst, ns IRNamespace) []string {
	mut lines := []string{}
	// Reference - store the path as a string
	src_path := c.storage_path_rid(fid, inst.source, ns)
	dest_path := c.storage_path_rid(fid, inst.result, ns)
	lines << 'data modify storage ${dest_path} set value "${src_path}"'
	return lines
}

fn (mut c Codegen) gen_struct_init(fid FID, bbid BBID, inst IRStructInit, ns IRNamespace) []string {
	mut lines := []string{}
	dest_path := c.storage_path_rid(fid, inst.result, ns)

	// Initialize struct as compound
	mut field_parts := []string{}
	for field_name, field_oid in inst.field_values {
		value := c.oid_to_nbt_value(fid, bbid, field_oid, ns)
		field_parts << '${field_name}: ${value}'
	}
	lines << 'data modify storage ${dest_path} set value {${field_parts.join(", ")}}'
	return lines
}

// ==================== Helper Functions ====================

// Get namespace parts by traversing parent chain
// Returns array like ["root", "sub", "subsub"] (root first)
fn (mut c Codegen) get_ns_parts(ns IRNamespace) []string {
	mut parts := []string{}
	mut current := ns
	for {
		parts << current.name
		if parent_nid := current.parent {
			current = c.builder.namespaces[parent_nid]
		} else {
			break
		}
	}
	// Reverse to get root first
	mut result := []string{}
	for i := parts.len - 1; i >= 0; i-- {
		result << parts[i]
	}
	return result
}

// Build storage path in format: <project>:<root_ns> <sub.ns.func.var>
// MC storage format is: first:second third.fourth.fifth
fn (mut c Codegen) build_storage_path(ns IRNamespace, components ...string) string {
	ns_parts := c.get_ns_parts(ns)

	if ns_parts.len == 0 {
		panic('Namespace has no parts')
	}

	root_ns := ns_parts[0]

	// Build the dotted part: sub-namespaces + components
	mut dotted := []string{}
	for i := 1; i < ns_parts.len; i++ {
		dotted << ns_parts[i]
	}
	for comp in components {
		dotted << comp
	}

	if dotted.len == 0 {
		return '${c.project_name}:${root_ns}'
	}
	return '${c.project_name}:${root_ns} ${dotted.join(".")}'
}

// Build function call path in format: <project_name>:<namespace/path/to/function>
// For function command: function example:macros/simple/command_1
fn (mut c Codegen) build_func_path(ns IRNamespace, components ...string) string {
	ns_parts := c.get_ns_parts(ns)

	// Build the slashed part: all namespace parts + components
	mut slashed := []string{}
	for part in ns_parts {
		slashed << part
	}
	for comp in components {
		slashed << comp
	}

	if slashed.len == 0 {
		return c.project_name
	}
	return '${c.project_name}:${slashed.join("/")}'
}

// Get storage kind for a reference
fn (mut c Codegen) get_ref_storage(fid FID, rid RID) StorageKind {
	func := c.builder.functions[fid]
	ref := func.refs[rid]

	match ref.value {
		VID {
			return c.builder.variables[ref.value].storage
		}
		IRBasicBlockArg {
			return ref.value.storage
		}
		IRFunctionArg {
			return ref.value.storage
		}
		IID {
			// Instruction results are registers by default
			return .register
		}
	}
}

// Get storage kind for an OID (constants are ephemeral/inline, RIDs depend on their ref)
fn (mut c Codegen) get_oid_storage(fid FID, oid OID) StorageKind {
	match oid {
		CID {
			// Constants are inline values, not stored anywhere
			return .effemeral
		}
		RID {
			return c.get_ref_storage(fid, oid)
		}
	}
}

// Get name for a reference (for macro substitution)
fn (mut c Codegen) get_ref_name(fid FID, rid RID) string {
	func := c.builder.functions[fid]
	ref := func.refs[rid]

	match ref.value {
		VID {
			return c.builder.variables[ref.value].name
		}
		IRBasicBlockArg {
			return ref.value.name
		}
		IRFunctionArg {
			return ref.value.name
		}
		IID {
			return '_tmp_${ref.value}'
		}
	}
}

// Get scoreboard player name for a reference
fn (mut c Codegen) scoreboard_player(fid FID, rid RID) string {
	func := c.builder.functions[fid]
	ns := c.builder.namespaces[func.namespace]
	ns_parts := c.get_ns_parts(ns)
	name := c.get_ref_name(fid, rid)
	return '${ns_parts.join("_")}_${func.name}_${name}'
}

// Get storage path for a reference
// Format: <project_name>:<ns> <func>.<varname>
// For function args: <project_name>:<ns> <func>.$args.<varname>
fn (mut c Codegen) storage_path_rid(fid FID, rid RID, ns IRNamespace) string {
	func := c.builder.functions[fid]
	ref := func.refs[rid]

	match ref.value {
		IRFunctionArg {
			// Function args come from $args storage
			return c.build_storage_path(ns, func.name, '\$args', ref.value.name)
		}
		IRBasicBlockArg {
			// BB args come from macro substitution, but their storage is in the BB's $args
			return c.build_storage_path(ns, func.name, '\$args', ref.value.name)
		}
		VID {
			return c.build_storage_path(ns, func.name, c.builder.variables[ref.value].name)
		}
		IID {
			return c.build_storage_path(ns, func.name, '_tmp_${ref.value}')
		}
	}
}

// Get storage path for an OID (only valid for RIDs with data storage)
fn (mut c Codegen) oid_to_storage_path(fid FID, oid OID, ns IRNamespace) string {
	match oid {
		CID {
			panic('Cannot get storage path for constant')
		}
		RID {
			return c.storage_path_rid(fid, oid, ns)
		}
	}
}

// Convert OID to a value for scoreboard set command
fn (mut c Codegen) oid_to_value_cmd(fid FID, bbid BBID, oid OID, ns IRNamespace) string {
	func := c.builder.functions[fid]
	match oid {
		CID {
			cnst := func.consts[oid]
			match cnst {
				IRIntConst {
					return '${cnst.value}'
				}
				else {
					return '0'
				}
			}
		}
		RID {
			// For scoreboard set, we can't use another score directly
			// This should be handled by caller
			return '0'
		}
	}
}

// Convert OID to storage command (value or from)
fn (mut c Codegen) oid_to_storage_cmd(fid FID, bbid BBID, oid OID, ns IRNamespace) string {
	func := c.builder.functions[fid]
	match oid {
		CID {
			cnst := func.consts[oid]
			match cnst {
				IRIntConst {
					return 'value ${cnst.value}'
				}
				IRFloatConst {
					return 'value ${cnst.value}d'
				}
				IRCharConst {
					return 'value "${cnst.value}"'
				}
				IRStringConst {
					mut s := ''
					for part in cnst.parts {
						match part {
							IRStringText { s += strip_quotes(part.text) }
							IRStringMacro { s += '\$(${c.get_ref_name(fid, part.value)})' }
						}
					}
					return 'value "${s}"'
				}
				else {
					return 'value {}'
				}
			}
		}
		RID {
			path := c.storage_path_rid(fid, oid, ns)
			return 'from storage ${path}'
		}
	}
}

// Convert OID to score player for operations
fn (mut c Codegen) oid_to_score_player(fid FID, bbid BBID, oid OID, ns IRNamespace) string {
	match oid {
		CID {
			// Constants need to be loaded into a temp score first
			return '#const ${c.project_name}'
		}
		RID {
			return c.scoreboard_player(fid, oid)
		}
	}
}

// Convert OID to NBT value for inline use
fn (mut c Codegen) oid_to_nbt_value(fid FID, bbid BBID, oid OID, ns IRNamespace) string {
	func := c.builder.functions[fid]
	match oid {
		CID {
			cnst := func.consts[oid]
			match cnst {
				IRIntConst { return '${cnst.value}' }
				IRFloatConst { return '${cnst.value}d' }
				IRCharConst { return '"${cnst.value}"' }
				IRStringConst {
					mut s := ''
					for part in cnst.parts {
						match part {
							IRStringText { s += strip_quotes(part.text) }
							IRStringMacro { s += '\$(${c.get_ref_name(fid, part.value)})' }
						}
					}
					return '"${s}"'
				}
				else { return '{}' }
			}
		}
		RID {
			// Can't inline RID directly, would need macro
			return '\$(${c.get_ref_name(fid, oid)})'
		}
	}
}

// Convert OID to index string for array access
fn (mut c Codegen) oid_to_index_str(fid FID, bbid BBID, oid OID, ns IRNamespace) string {
	func := c.builder.functions[fid]
	match oid {
		CID {
			cnst := func.consts[oid]
			match cnst {
				IRIntConst { return '${cnst.value}' }
				else { return '0' }
			}
		}
		RID {
			return '\$(${c.get_ref_name(fid, oid)})'
		}
	}
}

// Get raw value for reference macro
fn (mut c Codegen) rid_to_macro_ref(fid FID, rid RID, ns IRNamespace) string {
	// For &ref, we want the actual storage path
	return c.storage_path_rid(fid, rid, ns)
}

// Strip surrounding quotes from a string if present
fn strip_quotes(s string) string {
	if s.len >= 2 && s[0] == `"` && s[s.len - 1] == `"` {
		return s[1..s.len - 1]
	}
	return s
}
