[package]
name = "mcfunction-executor"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "mcfunction_executor"

[lints]
workspace = true

[dependencies]
mdl-compiler = { path = "../mdl-compiler" }
quartz_nbt = "0.2.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
