use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};

use super::{
    Anchor, CommandOutcomeExpectation, CompilerPolicy, CompletionExpectation, Coordinate,
    EntityCollection, EntityComparison, EntityRecord, ExactLimitContract, ExactLimitKind, Executor,
    MinecraftScenario, NbtValue, ObservationComparison, ObservationPath, ObservationSet,
    ObservationValue, OutcomeChannelExpectation, OwnedResource, ResourceLocation, ScenarioEntry,
    ScenarioMode, TestName, compare_observations,
};
use crate::{HarnessError, ServerConfig, ServerSandbox, TestServer};

const DRIVER_OBJECTIVE: &str = "mdl.ps1";
const MAX_OBSERVATION_DIFFERENCES: usize = 16;
const MAX_SEMANTIC_SUITE_CASES: usize = 64;
const MAX_ENTITY_QUERY_RESULTS: usize = 256;

/// One owned file in a compiled policy datapack.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DeploymentFile {
    path: PathBuf,
    bytes: Box<[u8]>,
}

impl DeploymentFile {
    /// Copies one emitted datapack file into an owned deployment artifact.
    #[must_use]
    pub fn new(path: impl Into<PathBuf>, bytes: impl Into<Box<[u8]>>) -> Self {
        Self {
            path: path.into(),
            bytes: bytes.into(),
        }
    }
}

/// Trusted single-line command generated by the Rust compiler bridge.
///
/// Commands are intentionally absent from [`super::ScenarioSpec`]. This escape
/// boundary adapts a compiler ABI to the test-owned scenario projection.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DriverCommand(Box<str>);

impl DriverCommand {
    /// Validates one nonempty command without a leading slash or physical newline.
    ///
    /// # Errors
    ///
    /// Returns an error for command injection or an empty command.
    pub fn new(value: impl Into<Box<str>>) -> Result<Self, ScenarioRunError> {
        let value = value.into();
        if value.is_empty() || value.starts_with('/') || value.contains(['\n', '\r']) {
            Err(ScenarioRunError::InvalidDeployment(format!(
                "invalid driver command {value:?}"
            )))
        } else {
            Ok(Self(value))
        }
    }
}

/// One compiled policy pack plus its typed-ABI adapter.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PolicyDeployment {
    policy: CompilerPolicy,
    pack_name: Box<str>,
    files: Box<[DeploymentFile]>,
    logical_entry: ScenarioEntry,
    prelude: Box<[DriverCommand]>,
    entry: ResourceLocation,
    publish: Box<[DriverCommand]>,
    artifacts: Box<[DeploymentFile]>,
}

impl PolicyDeployment {
    /// Creates one deployment assembled by compiler-aware Rust test code.
    #[must_use]
    pub fn new(
        policy: CompilerPolicy,
        pack_name: impl Into<Box<str>>,
        files: impl Into<Box<[DeploymentFile]>>,
        logical_entry: ScenarioEntry,
        prelude: impl Into<Box<[DriverCommand]>>,
        entry: ResourceLocation,
        publish: impl Into<Box<[DriverCommand]>>,
    ) -> Self {
        Self {
            policy,
            pack_name: pack_name.into(),
            files: files.into(),
            logical_entry,
            prelude: prelude.into(),
            entry,
            publish: publish.into(),
            artifacts: Box::new([]),
        }
    }

    /// Attaches compiler dumps/reports retained with a failed or preserved sandbox.
    #[must_use]
    pub fn with_artifacts(mut self, artifacts: impl Into<Box<[DeploymentFile]>>) -> Self {
        self.artifacts = artifacts.into();
        self
    }

    /// Returns the exact compiler policy represented by this artifact.
    #[must_use]
    pub const fn policy(&self) -> CompilerPolicy {
        self.policy
    }
}

/// Successful normalized observations for every policy product.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ScenarioRun {
    observations: Box<[PolicyObservation]>,
}

/// One borrowed semantic case installed into a shared server suite.
#[derive(Clone, Copy, Debug)]
pub struct SemanticScenarioCase<'a> {
    scenario: &'a MinecraftScenario,
    deployments: &'a [PolicyDeployment],
}

impl<'a> SemanticScenarioCase<'a> {
    /// Associates one validated scenario with its complete policy deployment matrix.
    #[must_use]
    pub const fn new(scenario: &'a MinecraftScenario, deployments: &'a [PolicyDeployment]) -> Self {
        Self {
            scenario,
            deployments,
        }
    }
}

impl ScenarioRun {
    /// Returns policy observations in scenario order.
    #[must_use]
    pub fn observations(&self) -> &[PolicyObservation] {
        &self.observations
    }
}

/// Complete normalized observation of one compiler policy execution.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PolicyObservation {
    policy: CompilerPolicy,
    state: ObservationSet,
    outcome: Option<CommandOutcomeObservation>,
}

impl PolicyObservation {
    /// Returns the compiler policy.
    #[must_use]
    pub const fn policy(&self) -> CompilerPolicy {
        self.policy
    }

    /// Returns the declared world-state projection.
    #[must_use]
    pub const fn state(&self) -> &ObservationSet {
        &self.state
    }

    /// Returns command channels when the scenario requested them.
    #[must_use]
    pub const fn outcome(&self) -> Option<CommandOutcomeObservation> {
        self.outcome
    }
}

/// Independently captured command channels and outer continuation state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CommandOutcomeObservation {
    success: Option<bool>,
    result: Option<i32>,
    continued: bool,
}

impl CommandOutcomeObservation {
    /// Returns `None` when the nested command never published a success channel.
    #[must_use]
    pub const fn success(self) -> Option<bool> {
        self.success
    }

    /// Returns `None` when the nested command never published a result channel.
    #[must_use]
    pub const fn result(self) -> Option<i32> {
        self.result
    }

    /// Returns whether the generated wrapper reached its post-invocation line.
    #[must_use]
    pub const fn continued(self) -> bool {
        self.continued
    }
}

/// Runs one semantic scenario across its complete policy matrix in one server.
///
/// The deployment adapter may read/write compiler ABI slots, but it must publish
/// results into the scenario's declared test-owned projection. Assertions never
/// inspect compiler-private activation storage or generated function layout.
///
/// # Errors
///
/// Returns validation, vanilla harness, query parsing, semantic mismatch, or policy
/// differential errors. Failures after server startup preserve the whole sandbox.
pub fn run_semantic_policy_scenario(
    config: &ServerConfig,
    preserve_success: bool,
    scenario: &MinecraftScenario,
    deployments: &[PolicyDeployment],
) -> Result<ScenarioRun, ScenarioRunError> {
    let runs = run_semantic_policy_suite(
        config,
        preserve_success,
        &[SemanticScenarioCase::new(scenario, deployments)],
    )?;
    runs.into_vec().pop().ok_or_else(|| {
        ScenarioRunError::InvalidDeployment("semantic suite returned no scenario run".to_owned())
    })
}

/// Runs multiple semantic scenarios in one disposable vanilla-server lifecycle.
///
/// Every deployment and generated driver is materialized before Java starts. Cases
/// execute in caller order, while every case still runs its complete policy matrix
/// with independent state reset and normalized comparison.
///
/// # Errors
///
/// Returns validation, installation, vanilla, query, or comparison errors. Any
/// failure preserves the shared sandbox and identifies the active scenario.
pub fn run_semantic_policy_suite(
    config: &ServerConfig,
    preserve_success: bool,
    cases: &[SemanticScenarioCase<'_>],
) -> Result<Box<[ScenarioRun]>, ScenarioRunError> {
    validate_semantic_suite(cases)?;
    let mut sandbox = ServerSandbox::create(preserve_success)?;
    for case in cases {
        if let Err(error) = install_deployments(&sandbox, case.deployments)
            .and_then(|()| install_driver(&sandbox, case.scenario, case.deployments))
        {
            let root = sandbox.root().to_path_buf();
            write_failure_report(&root, case.scenario, &error, "");
            sandbox.set_preserve(true);
            return Err(ScenarioRunError::PreservedFailure {
                sandbox: root,
                source: Box::new(error),
            });
        }
    }

    let mut server = sandbox.start(config)?;
    let root = server.root().to_path_buf();
    let mut runs = Vec::with_capacity(cases.len());
    for case in cases {
        match execute_scenario(&mut server, case.scenario, case.deployments) {
            Ok(run) => runs.push(run),
            Err(error) => {
                write_failure_report(&root, case.scenario, &error, &server.recent_log());
                server.preserve_sandbox();
                return Err(ScenarioRunError::PreservedFailure {
                    sandbox: root,
                    source: Box::new(error),
                });
            }
        }
    }
    server.shutdown()?;
    Ok(runs.into_boxed_slice())
}

fn validate_semantic_suite(cases: &[SemanticScenarioCase<'_>]) -> Result<(), ScenarioRunError> {
    if cases.is_empty() {
        return Err(ScenarioRunError::InvalidDeployment(
            "semantic suite contains no scenarios".to_owned(),
        ));
    }
    if cases.len() > MAX_SEMANTIC_SUITE_CASES {
        return Err(ScenarioRunError::InvalidDeployment(format!(
            "semantic suite contains {} scenarios, limit is {MAX_SEMANTIC_SUITE_CASES}",
            cases.len()
        )));
    }
    let mut generations = BTreeSet::new();
    let mut pack_names = BTreeSet::new();
    for case in cases {
        validate_runner_surface(case.scenario, case.deployments)?;
        if !generations.insert(case.scenario.generation()) {
            return Err(ScenarioRunError::InvalidDeployment(format!(
                "duplicate semantic-suite generation {}",
                case.scenario.generation().get()
            )));
        }
        for deployment in case.deployments {
            if !pack_names.insert(deployment.pack_name.as_ref()) {
                return Err(ScenarioRunError::InvalidDeployment(format!(
                    "duplicate semantic-suite pack name {:?}",
                    deployment.pack_name
                )));
            }
        }
    }
    Ok(())
}

/// Runs one exact-limit scenario without installing or invoking a wrapper function.
///
/// Deployment preludes execute as independent console roots before the measured
/// invocation. Deployment publication and every observation execute as independent
/// console roots after it. Consequently none of the harness commands consume the
/// measured root's sequence or fork budget.
///
/// # Errors
///
/// Returns validation, vanilla harness, query parsing, limit-completion mismatch,
/// semantic mismatch, or policy-differential errors. Failures after server startup
/// preserve the complete sandbox.
pub fn run_exact_limit_policy_scenario(
    config: &ServerConfig,
    preserve_success: bool,
    scenario: &MinecraftScenario,
    deployments: &[PolicyDeployment],
) -> Result<ScenarioRun, ScenarioRunError> {
    let contract = validate_exact_limit_surface(scenario, deployments)?;
    let mut sandbox = ServerSandbox::create(preserve_success)?;
    if let Err(error) = install_deployments(&sandbox, deployments)
        .and_then(|()| install_exact_prelude_support(&sandbox, scenario, deployments))
    {
        let root = sandbox.root().to_path_buf();
        write_failure_report(&root, scenario, &error, "");
        sandbox.set_preserve(true);
        return Err(ScenarioRunError::PreservedFailure {
            sandbox: root,
            source: Box::new(error),
        });
    }

    let mut server = sandbox.start(config)?;
    let root = server.root().to_path_buf();
    let result = execute_exact_limit_scenario(&mut server, scenario, deployments, contract);
    let run = match result {
        Ok(run) => run,
        Err(error) => {
            write_failure_report(&root, scenario, &error, &server.recent_log());
            server.preserve_sandbox();
            return Err(ScenarioRunError::PreservedFailure {
                sandbox: root,
                source: Box::new(error),
            });
        }
    };
    server.shutdown()?;
    Ok(run)
}

fn install_exact_prelude_support(
    sandbox: &ServerSandbox,
    scenario: &MinecraftScenario,
    deployments: &[PolicyDeployment],
) -> Result<(), ScenarioRunError> {
    if deployments
        .iter()
        .all(|deployment| deployment.prelude.is_empty())
    {
        return Ok(());
    }
    let namespace = driver_namespace(scenario);
    sandbox.install_datapack(
        &format!("{namespace}_support"),
        [
            (
                PathBuf::from("pack.mcmeta"),
                concat!(
                    "{\n",
                    "  \"pack\": {\n",
                    "    \"description\": \"MDL PS-1 exact-limit prelude barrier\",\n",
                    "    \"min_format\": [107, 1],\n",
                    "    \"max_format\": [107, 1]\n",
                    "  }\n",
                    "}\n"
                )
                .as_bytes()
                .to_vec(),
            ),
            (
                PathBuf::from(format!(
                    "data/{namespace}/function/prelude_barrier.mcfunction"
                )),
                prelude_barrier_contents(scenario)?.into_bytes(),
            ),
        ],
    )?;
    Ok(())
}

fn validate_runner_surface(
    scenario: &MinecraftScenario,
    deployments: &[PolicyDeployment],
) -> Result<(), ScenarioRunError> {
    if !matches!(scenario.mode(), ScenarioMode::Semantic { .. }) {
        return Err(ScenarioRunError::UnsupportedSurface(
            "the policy runner accepts semantic scenarios only".to_owned(),
        ));
    }
    validate_score_runner_surface(scenario, deployments)
}

fn validate_exact_limit_surface<'a>(
    scenario: &'a MinecraftScenario,
    deployments: &[PolicyDeployment],
) -> Result<&'a ExactLimitContract, ScenarioRunError> {
    let ScenarioMode::ExactLimit(contract) = scenario.mode() else {
        return Err(ScenarioRunError::UnsupportedSurface(
            "the exact-limit runner accepts exact-limit scenarios only".to_owned(),
        ));
    };
    validate_score_runner_surface(scenario, deployments)?;
    Ok(contract)
}

fn validate_score_runner_surface(
    scenario: &MinecraftScenario,
    deployments: &[PolicyDeployment],
) -> Result<(), ScenarioRunError> {
    for resource in scenario.owned_resources() {
        if matches!(resource, OwnedResource::Objective(objective) if objective.as_str() == DRIVER_OBJECTIVE)
        {
            return Err(ScenarioRunError::UnsupportedSurface(format!(
                "scenario objective {DRIVER_OBJECTIVE} collides with the runner scratch objective"
            )));
        }
        if !matches!(
            resource,
            OwnedResource::Objective(_)
                | OwnedResource::Storage(_)
                | OwnedResource::EntityTag(_)
                | OwnedResource::ForcedChunk { .. }
        ) {
            return Err(ScenarioRunError::UnsupportedSurface(format!(
                "the first policy runner cannot set up {resource:?}"
            )));
        }
    }
    if scenario
        .initial()
        .iter()
        .any(|(_, value)| !matches!(value, ObservationValue::Score(_) | ObservationValue::Nbt(_)))
    {
        return Err(ScenarioRunError::UnsupportedSurface(
            "the policy runner initializes scoreboard and storage NBT values only".to_owned(),
        ));
    }
    if scenario.expected().iter().any(|(_, value)| {
        !matches!(
            value,
            ObservationValue::Score(_) | ObservationValue::Nbt(_) | ObservationValue::Entities(_)
        )
    }) {
        return Err(ScenarioRunError::UnsupportedSurface(
            "the policy runner observes scoreboard, storage NBT, and entity projections only"
                .to_owned(),
        ));
    }

    let requested = scenario.policies().iter().copied().collect::<BTreeSet<_>>();
    let mut supplied = BTreeSet::new();
    for deployment in deployments {
        super::super::validate_component(&deployment.pack_name, "policy pack name")?;
        if &deployment.logical_entry != scenario.entry() {
            return Err(ScenarioRunError::InvalidDeployment(format!(
                "deployment {} resolves {:?}, but scenario requests {:?}",
                deployment.policy,
                deployment.logical_entry,
                scenario.entry()
            )));
        }
        if !supplied.insert(deployment.policy) {
            return Err(ScenarioRunError::InvalidDeployment(format!(
                "duplicate deployment for {}",
                deployment.policy
            )));
        }
    }
    if requested != supplied {
        return Err(ScenarioRunError::InvalidDeployment(format!(
            "deployment policies {supplied:?} do not match scenario policies {requested:?}"
        )));
    }
    Ok(())
}

fn install_deployments(
    sandbox: &ServerSandbox,
    deployments: &[PolicyDeployment],
) -> Result<(), ScenarioRunError> {
    for deployment in deployments {
        sandbox.install_datapack(
            &deployment.pack_name,
            deployment
                .files
                .iter()
                .map(|file| (file.path.as_path(), file.bytes.as_ref())),
        )?;
        if !deployment.artifacts.is_empty() {
            sandbox.install_artifacts(
                &deployment.pack_name,
                deployment
                    .artifacts
                    .iter()
                    .map(|file| (file.path.as_path(), file.bytes.as_ref())),
            )?;
        }
    }
    Ok(())
}

fn install_driver(
    sandbox: &ServerSandbox,
    scenario: &MinecraftScenario,
    deployments: &[PolicyDeployment],
) -> Result<(), ScenarioRunError> {
    let namespace = driver_namespace(scenario);
    let pack_name = format!("{namespace}_pack");
    let mut files = vec![(
        PathBuf::from("pack.mcmeta"),
        concat!(
            "{\n",
            "  \"pack\": {\n",
            "    \"description\": \"MDL PS-1 semantic scenario driver\",\n",
            "    \"min_format\": [107, 1],\n",
            "    \"max_format\": [107, 1]\n",
            "  }\n",
            "}\n"
        )
        .as_bytes()
        .to_vec(),
    )];
    files.push((
        PathBuf::from(format!(
            "data/{namespace}/function/prelude_barrier.mcfunction"
        )),
        prelude_barrier_contents(scenario)?.into_bytes(),
    ));
    for (index, policy) in scenario.policies().iter().enumerate() {
        let deployment = deployments
            .iter()
            .find(|deployment| deployment.policy == *policy)
            .ok_or_else(|| {
                ScenarioRunError::InvalidDeployment(format!(
                    "missing deployment for policy {policy}"
                ))
            })?;
        let mut commands = Vec::new();
        let invocation = render_invocation(scenario, &deployment.entry);
        if expected_outcome(scenario).is_some() {
            let storage = outcome_storage(scenario);
            commands.push(format!(
                "execute store success storage {storage} p{index}.success byte 1 store result storage {storage} p{index}.result int 1 run {invocation}"
            ));
        } else {
            commands.push(invocation);
        }
        commands.push(format!(
            "scoreboard players set {} {DRIVER_OBJECTIVE} 1",
            continuation_holder(index)
        ));
        commands.extend(
            deployment
                .publish
                .iter()
                .map(|command| command.0.to_string()),
        );
        let contents = format!("{}\n", commands.join("\n"));
        files.push((
            PathBuf::from(format!(
                "data/{namespace}/function/policy_{index}.mcfunction"
            )),
            contents.into_bytes(),
        ));
    }
    sandbox.install_datapack(&pack_name, files)?;
    Ok(())
}

fn execute_scenario(
    server: &mut TestServer,
    scenario: &MinecraftScenario,
    deployments: &[PolicyDeployment],
) -> Result<ScenarioRun, ScenarioRunError> {
    server.command(&format!(
        "scoreboard objectives add {DRIVER_OBJECTIVE} dummy"
    ))?;
    server.wait_for_command_log("Created new objective")?;
    setup_owned_resources(server, scenario)?;

    let namespace = driver_namespace(scenario);
    let mut observations: Vec<PolicyObservation> = Vec::with_capacity(deployments.len());
    for (index, policy) in scenario.policies().iter().enumerate() {
        let deployment = deployments
            .iter()
            .find(|deployment| deployment.policy == *policy)
            .ok_or_else(|| {
                ScenarioRunError::InvalidDeployment(format!(
                    "missing deployment for policy {policy}"
                ))
            })?;
        reset_owned_state(server, scenario)?;
        apply_initial_state(server, scenario.initial())?;
        for command in &deployment.prelude {
            server.command(&command.0)?;
        }
        settle_prelude(server, scenario, &deployment.prelude)?;
        server.command(&format!(
            "scoreboard players set {} {DRIVER_OBJECTIVE} 0",
            continuation_holder(index)
        ))?;
        if expected_outcome(scenario).is_some() {
            server.command(&format!(
                "data remove storage {} p{index}",
                outcome_storage(scenario)
            ))?;
        }
        server.command(&format!("function {namespace}:policy_{index}"))?;
        let barrier = completion_marker(scenario, index);
        server.command(&format!("say {barrier}"))?;
        server.wait_for_command_log(&barrier)?;
        let actual = query_expected_projection(server, scenario.expected(), index)?;
        let outcome = expected_outcome(scenario)
            .map(|_| query_outcome(server, scenario, index))
            .transpose()?;
        let comparison =
            compare_observations(scenario.expected(), &actual, MAX_OBSERVATION_DIFFERENCES);
        if !comparison.is_equal() {
            return Err(ScenarioRunError::ObservationMismatch {
                scenario: scenario.id().to_string(),
                policy: *policy,
                comparison,
            });
        }
        if let (Some(expected), Some(outcome)) = (expected_outcome(scenario), outcome)
            && !outcome_matches(expected, outcome)
        {
            return Err(ScenarioRunError::OutcomeMismatch {
                scenario: scenario.id().to_string(),
                policy: *policy,
                expected,
                actual: outcome,
            });
        }
        if let Some(reference) = observations.first() {
            let comparison =
                compare_observations(reference.state(), &actual, MAX_OBSERVATION_DIFFERENCES);
            if !comparison.is_equal() {
                return Err(ScenarioRunError::PolicyMismatch {
                    reference: reference.policy(),
                    actual: *policy,
                    comparison,
                });
            }
            if reference.outcome() != outcome {
                return Err(ScenarioRunError::PolicyOutcomeMismatch {
                    reference: reference.policy(),
                    actual: *policy,
                    reference_outcome: reference.outcome(),
                    actual_outcome: outcome,
                });
            }
        }
        observations.push(PolicyObservation {
            policy: *policy,
            state: actual,
            outcome,
        });
    }
    cleanup_owned_state(server, scenario)?;
    server.command(&format!("scoreboard objectives remove {DRIVER_OBJECTIVE}"))?;
    Ok(ScenarioRun {
        observations: observations.into_boxed_slice(),
    })
}

fn execute_exact_limit_scenario(
    server: &mut TestServer,
    scenario: &MinecraftScenario,
    deployments: &[PolicyDeployment],
    contract: &ExactLimitContract,
) -> Result<ScenarioRun, ScenarioRunError> {
    server.command(&format!(
        "scoreboard objectives add {DRIVER_OBJECTIVE} dummy"
    ))?;
    server.wait_for_command_log("Created new objective")?;
    setup_owned_resources(server, scenario)?;

    let mut observations: Vec<PolicyObservation> = Vec::with_capacity(deployments.len());
    for (index, policy) in scenario.policies().iter().enumerate() {
        let deployment = deployments
            .iter()
            .find(|deployment| deployment.policy == *policy)
            .ok_or_else(|| {
                ScenarioRunError::InvalidDeployment(format!(
                    "missing deployment for policy {policy}"
                ))
            })?;
        reset_owned_state(server, scenario)?;
        apply_initial_state(server, scenario.initial())?;
        initialize_exact_completion(server, contract)?;
        for command in &deployment.prelude {
            server.command(&command.0)?;
        }
        settle_prelude(server, scenario, &deployment.prelude)?;

        set_limit_gamerule(server, contract.kind(), contract.configured_limit())?;
        server.command(&render_invocation(scenario, &deployment.entry))?;
        let barrier = completion_marker(scenario, index);
        server.command(&format!("say {barrier}"))?;
        server.wait_for_command_log(&barrier)?;
        set_limit_gamerule(server, contract.kind(), 65_536)?;

        for command in &deployment.publish {
            server.command(&command.0)?;
        }
        let actual = query_expected_projection(server, scenario.expected(), index)?;
        let completed = query_exact_completion(server, contract)?;
        if completed != contract.root_completes() {
            return Err(ScenarioRunError::LimitCompletionMismatch {
                scenario: scenario.id().to_string(),
                policy: *policy,
                kind: contract.kind(),
                configured_limit: contract.configured_limit(),
                expected: contract.root_completes(),
                actual: completed,
            });
        }
        let comparison =
            compare_observations(scenario.expected(), &actual, MAX_OBSERVATION_DIFFERENCES);
        if !comparison.is_equal() {
            return Err(ScenarioRunError::ObservationMismatch {
                scenario: scenario.id().to_string(),
                policy: *policy,
                comparison,
            });
        }
        if let Some(reference) = observations.first() {
            let comparison =
                compare_observations(reference.state(), &actual, MAX_OBSERVATION_DIFFERENCES);
            if !comparison.is_equal() {
                return Err(ScenarioRunError::PolicyMismatch {
                    reference: reference.policy(),
                    actual: *policy,
                    comparison,
                });
            }
        }
        observations.push(PolicyObservation {
            policy: *policy,
            state: actual,
            outcome: None,
        });
    }

    cleanup_owned_state(server, scenario)?;
    server.command(&format!("scoreboard objectives remove {DRIVER_OBJECTIVE}"))?;
    Ok(ScenarioRun {
        observations: observations.into_boxed_slice(),
    })
}

fn settle_prelude(
    server: &mut TestServer,
    scenario: &MinecraftScenario,
    prelude: &[DriverCommand],
) -> Result<(), ScenarioRunError> {
    if prelude.is_empty() {
        return Ok(());
    }
    let namespace = driver_namespace(scenario);
    let marker = prelude_barrier(scenario);
    server.command(&format!(
        "schedule function {namespace}:prelude_barrier 1t replace"
    ))?;
    server.wait_for_command_log(&marker)?;
    Ok(())
}

fn prelude_barrier(scenario: &MinecraftScenario) -> String {
    format!("MDL_PS1_PRELUDE_{:016x}", scenario.generation().get())
}

fn prelude_barrier_contents(scenario: &MinecraftScenario) -> Result<String, ScenarioRunError> {
    let namespace = driver_namespace(scenario);
    let mut commands = vec![format!(
        "scoreboard players set #prelude_ready {DRIVER_OBJECTIVE} 1"
    )];
    for (index, (path, value)) in scenario.expected().iter().enumerate() {
        let (
            ObservationPath::Entities { tag, .. },
            ObservationValue::Entities(EntityCollection::Multiset(records)),
        ) = (path, value)
        else {
            continue;
        };
        let cardinality = records
            .values()
            .try_fold(0usize, |total, count| total.checked_add(*count))
            .ok_or_else(|| {
                ScenarioRunError::InvalidDeployment(format!(
                    "entity expectation for tag {tag} overflows its cardinality"
                ))
            })?;
        if cardinality > MAX_ENTITY_QUERY_RESULTS {
            return Err(ScenarioRunError::InvalidDeployment(format!(
                "entity expectation for tag {tag} contains {cardinality} records, limit is {MAX_ENTITY_QUERY_RESULTS}"
            )));
        }
        let holder = format!("#prelude_entities_{index}");
        commands.push(format!(
            "execute store result score {holder} {DRIVER_OBJECTIVE} run execute if entity @e[tag={tag}]"
        ));
        commands.push(format!(
            "execute unless score {holder} {DRIVER_OBJECTIVE} matches {cardinality} run scoreboard players set #prelude_ready {DRIVER_OBJECTIVE} 0"
        ));
    }
    commands.push(format!(
        "execute if score #prelude_ready {DRIVER_OBJECTIVE} matches 1 run say {}",
        prelude_barrier(scenario)
    ));
    commands.push(format!(
        "execute unless score #prelude_ready {DRIVER_OBJECTIVE} matches 1 run schedule function {namespace}:prelude_barrier 1t replace"
    ));
    Ok(format!("{}\n", commands.join("\n")))
}

fn initialize_exact_completion(
    server: &mut TestServer,
    contract: &ExactLimitContract,
) -> Result<(), ScenarioRunError> {
    let ObservationPath::Score { holder, objective } = contract.completion() else {
        return Err(ScenarioRunError::UnsupportedSurface(
            "exact-limit completion reached the runner without a score path".to_owned(),
        ));
    };
    server.command(&format!("scoreboard players set {holder} {objective} 0"))?;
    Ok(())
}

fn query_exact_completion(
    server: &mut TestServer,
    contract: &ExactLimitContract,
) -> Result<bool, ScenarioRunError> {
    let ObservationPath::Score { holder, objective } = contract.completion() else {
        return Err(ScenarioRunError::UnsupportedSurface(
            "exact-limit completion reached the runner without a score path".to_owned(),
        ));
    };
    match get_score(server, holder, objective.as_str())? {
        0 => Ok(false),
        1 => Ok(true),
        value => Err(ScenarioRunError::QueryParse(format!(
            "exact-limit completion marker contained {value}, expected 0 or 1"
        ))),
    }
}

fn set_limit_gamerule(
    server: &mut TestServer,
    kind: ExactLimitKind,
    value: u32,
) -> Result<(), ScenarioRunError> {
    let name = match kind {
        ExactLimitKind::Sequence => "max_command_sequence_length",
        ExactLimitKind::Fork => "max_command_forks",
    };
    server.command(&format!("gamerule minecraft:{name} {value}"))?;
    server.wait_for_command_log(&format!("Gamerule {name} is now set to: {value}"))?;
    Ok(())
}

fn reset_owned_state(
    server: &mut TestServer,
    scenario: &MinecraftScenario,
) -> Result<(), ScenarioRunError> {
    for resource in scenario.owned_resources() {
        match resource {
            OwnedResource::Objective(objective) => {
                server.command(&format!("scoreboard players reset * {objective}"))?;
            }
            OwnedResource::Storage(storage) => {
                clear_storage_paths(server, scenario, storage)?;
            }
            OwnedResource::EntityTag(tag) => {
                server.command(&format!("kill @e[tag={tag}]"))?;
            }
            OwnedResource::ForcedChunk { .. } => {}
            OwnedResource::Block { .. }
            | OwnedResource::Bossbar(_)
            | OwnedResource::Gamerule(_) => {
                return Err(ScenarioRunError::UnsupportedSurface(format!(
                    "unsupported reset resource {resource:?}"
                )));
            }
        }
    }
    Ok(())
}

fn apply_initial_state(
    server: &mut TestServer,
    initial: &ObservationSet,
) -> Result<(), ScenarioRunError> {
    for (path, value) in initial.iter() {
        match (path, value) {
            (
                ObservationPath::Score { holder, objective },
                ObservationValue::Score(Some(value)),
            ) => {
                server.command(&format!(
                    "scoreboard players set {holder} {objective} {value}"
                ))?;
            }
            (ObservationPath::Score { .. }, ObservationValue::Score(None))
            | (ObservationPath::Storage { .. }, ObservationValue::Nbt(None)) => {}
            (ObservationPath::Storage { storage, path }, ObservationValue::Nbt(Some(value))) => {
                server.command(&format!(
                    "data modify storage {storage} {path} set value {value}"
                ))?;
            }
            _ => {
                return Err(ScenarioRunError::UnsupportedSurface(
                    "unsupported initial-state projection reached the runner".to_owned(),
                ));
            }
        }
    }
    Ok(())
}

fn query_expected_projection(
    server: &mut TestServer,
    expected: &ObservationSet,
    policy_index: usize,
) -> Result<ObservationSet, ScenarioRunError> {
    let mut actual = Vec::with_capacity(expected.iter().len());
    for (observation_index, (path, expected_value)) in expected.iter().enumerate() {
        let value =
            match path {
                ObservationPath::Score { holder, objective } => {
                    ObservationValue::Score(query_score(
                        server,
                        holder,
                        objective.as_str(),
                        policy_index,
                        observation_index,
                    )?)
                }
                ObservationPath::Storage { storage, path } => ObservationValue::Nbt(
                    query_storage_nbt(server, storage, path, policy_index, observation_index)?,
                ),
                ObservationPath::Entities { tag, comparison } => {
                    ObservationValue::Entities(query_entities(
                        server,
                        tag,
                        *comparison,
                        expected_value,
                        policy_index,
                        observation_index,
                    )?)
                }
                ObservationPath::Block { .. } | ObservationPath::LogEffects { .. } => {
                    return Err(ScenarioRunError::UnsupportedSurface(
                        "unsupported expectation reached the runner".to_owned(),
                    ));
                }
            };
        actual.push((path.clone(), value));
    }
    ObservationSet::try_new(actual).map_err(ScenarioRunError::from)
}

fn query_score(
    server: &mut TestServer,
    holder: &str,
    objective: &str,
    policy_index: usize,
    observation_index: usize,
) -> Result<Option<i32>, ScenarioRunError> {
    let presence = format!("#p{policy_index}_{observation_index}");
    server.command(&format!(
        "execute store success score {presence} {DRIVER_OBJECTIVE} run scoreboard players get {holder} {objective}"
    ))?;
    let present = get_score(server, &presence, DRIVER_OBJECTIVE)?;
    match present {
        0 => Ok(None),
        1 => get_score(server, holder, objective).map(Some),
        other => Err(ScenarioRunError::QueryParse(format!(
            "presence probe {presence} returned {other}, expected 0 or 1"
        ))),
    }
}

fn query_storage_nbt(
    server: &mut TestServer,
    storage: &ResourceLocation,
    path: &str,
    policy_index: usize,
    observation_index: usize,
) -> Result<Option<NbtValue>, ScenarioRunError> {
    let presence = format!("#n{policy_index}_{observation_index}_p");
    server.command(&format!(
        "execute store success score {presence} {DRIVER_OBJECTIVE} run data get storage {storage} {path}"
    ))?;
    if get_score(server, &presence, DRIVER_OBJECTIVE)? == 0 {
        return Ok(None);
    }
    server.command(&format!("data get storage {storage} {path}"))?;
    let line = server.wait_for_command_log(" has the following contents: ")?;
    parse_nbt_feedback(&line).map(Some)
}

fn parse_nbt_feedback(line: &str) -> Result<NbtValue, ScenarioRunError> {
    const MARKER: &str = " has the following contents: ";
    let (_, value) = line.rsplit_once(MARKER).ok_or_else(|| {
        ScenarioRunError::QueryParse(format!("expected NBT feedback, got {line:?}"))
    })?;
    NbtValue::parse_snbt(value).map_err(|error| {
        ScenarioRunError::QueryParse(format!("invalid bounded SNBT in {line:?}: {error}"))
    })
}

fn query_entities(
    server: &mut TestServer,
    tag: &TestName,
    comparison: EntityComparison,
    expected: &ObservationValue,
    policy_index: usize,
    observation_index: usize,
) -> Result<EntityCollection, ScenarioRunError> {
    let ObservationValue::Entities(expected) = expected else {
        return Err(ScenarioRunError::QueryParse(
            "entity path reached a non-entity expectation".to_owned(),
        ));
    };
    if !expected.is_cardinality_only() {
        return Err(ScenarioRunError::UnsupportedSurface(
            "the PS-1 entity runner currently supports cardinality-only records".to_owned(),
        ));
    }
    let checkpoint = server.log_checkpoint();
    server.command(&format!("execute as @e[tag={tag}] run data get entity @s"))?;
    let barrier = format!("MDL_PS1_ENTITY_QUERY_{policy_index}_{observation_index}");
    server.command(&format!("say {barrier}"))?;
    server.wait_for_command_log(&barrier)?;
    let count = server
        .matching_log_lines_since(checkpoint, " has the following entity data: ")?
        .len();
    if count > MAX_ENTITY_QUERY_RESULTS {
        return Err(ScenarioRunError::QueryParse(format!(
            "entity query for tag {tag} returned {count} records, limit is {MAX_ENTITY_QUERY_RESULTS}"
        )));
    }
    let record = EntityRecord::new(BTreeMap::new());
    Ok(match comparison {
        EntityComparison::Set => {
            EntityCollection::Set((count != 0).then_some(record).into_iter().collect())
        }
        EntityComparison::Multiset => EntityCollection::Multiset(
            (count != 0)
                .then_some((record, count))
                .into_iter()
                .collect(),
        ),
    })
}

fn get_score(
    server: &mut TestServer,
    holder: &str,
    objective: &str,
) -> Result<i32, ScenarioRunError> {
    server.command(&format!("scoreboard players get {holder} {objective}"))?;
    let line = server.wait_for_command_log(&format!("{holder} has"))?;
    parse_score_feedback(&line, holder, objective).ok_or_else(|| {
        ScenarioRunError::QueryParse(format!(
            "expected score feedback for {holder} [{objective}], got {line:?}"
        ))
    })
}

fn query_outcome(
    server: &mut TestServer,
    scenario: &MinecraftScenario,
    policy_index: usize,
) -> Result<CommandOutcomeObservation, ScenarioRunError> {
    let storage = outcome_storage(scenario);
    let success = query_storage_i32(
        server,
        &storage,
        &format!("p{policy_index}.success"),
        policy_index,
        "success",
    )?
    .map(|value| match value {
        0 => Ok(false),
        1 => Ok(true),
        _ => Err(ScenarioRunError::QueryParse(format!(
            "stored success channel contained {value}, expected 0 or 1"
        ))),
    })
    .transpose()?;
    let result = query_storage_i32(
        server,
        &storage,
        &format!("p{policy_index}.result"),
        policy_index,
        "result",
    )?;
    let continued = get_score(server, &continuation_holder(policy_index), DRIVER_OBJECTIVE)?;
    let continued = match continued {
        0 => false,
        1 => true,
        value => {
            return Err(ScenarioRunError::QueryParse(format!(
                "continuation marker contained {value}, expected 0 or 1"
            )));
        }
    };
    Ok(CommandOutcomeObservation {
        success,
        result,
        continued,
    })
}

fn query_storage_i32(
    server: &mut TestServer,
    storage: &str,
    path: &str,
    policy_index: usize,
    label: &str,
) -> Result<Option<i32>, ScenarioRunError> {
    let presence = format!("#o{policy_index}_{label}_p");
    server.command(&format!(
        "execute store success score {presence} {DRIVER_OBJECTIVE} run data get storage {storage} {path}"
    ))?;
    if get_score(server, &presence, DRIVER_OBJECTIVE)? == 0 {
        return Ok(None);
    }
    let value_holder = format!("#o{policy_index}_{label}_v");
    server.command(&format!(
        "execute store result score {value_holder} {DRIVER_OBJECTIVE} run data get storage {storage} {path} 1"
    ))?;
    get_score(server, &value_holder, DRIVER_OBJECTIVE).map(Some)
}

fn expected_outcome(scenario: &MinecraftScenario) -> Option<CommandOutcomeExpectation> {
    match scenario.mode() {
        ScenarioMode::Semantic { outcome } => *outcome,
        ScenarioMode::ExactLimit(_) | ScenarioMode::Measurement { .. } => None,
    }
}

fn outcome_matches(expected: CommandOutcomeExpectation, actual: CommandOutcomeObservation) -> bool {
    channel_matches(expected.success(), actual.success())
        && channel_matches(expected.result(), actual.result())
        && match expected.continuation() {
            CompletionExpectation::Continued => actual.continued(),
            CompletionExpectation::Interrupted => !actual.continued(),
            CompletionExpectation::Unobserved => true,
        }
}

fn channel_matches<T: Copy + Eq>(
    expected: OutcomeChannelExpectation<T>,
    actual: Option<T>,
) -> bool {
    match expected {
        OutcomeChannelExpectation::Unobserved => true,
        OutcomeChannelExpectation::Unavailable => actual.is_none(),
        OutcomeChannelExpectation::Value(expected) => actual == Some(expected),
    }
}

fn parse_score_feedback(line: &str, holder: &str, objective: &str) -> Option<i32> {
    let prefix = format!("{holder} has ");
    let suffix = format!(" [{objective}]");
    let start = line.rfind(&prefix)? + prefix.len();
    let tail = &line[start..];
    let end = tail.find(&suffix)?;
    tail[..end].parse().ok()
}

fn cleanup_owned_state(
    server: &mut TestServer,
    scenario: &MinecraftScenario,
) -> Result<(), ScenarioRunError> {
    for resource in scenario.cleanup_resources() {
        match resource {
            OwnedResource::Objective(objective) => {
                server.command(&format!("scoreboard objectives remove {objective}"))?;
            }
            OwnedResource::Storage(storage) => {
                clear_storage_paths(server, scenario, storage)?;
            }
            OwnedResource::EntityTag(tag) => {
                server.command(&format!("kill @e[tag={tag}]"))?;
            }
            OwnedResource::ForcedChunk { dimension, x, z } => {
                let (x, z) = chunk_block_coordinates(*x, *z)?;
                server.command(&format!(
                    "execute in {dimension} run forceload remove {x} {z}"
                ))?;
            }
            OwnedResource::Block { .. }
            | OwnedResource::Bossbar(_)
            | OwnedResource::Gamerule(_) => {
                return Err(ScenarioRunError::UnsupportedSurface(format!(
                    "unsupported cleanup resource {resource:?}"
                )));
            }
        }
    }
    Ok(())
}

fn clear_storage_paths(
    server: &mut TestServer,
    scenario: &MinecraftScenario,
    storage: &ResourceLocation,
) -> Result<(), ScenarioRunError> {
    let paths = scenario
        .initial()
        .iter()
        .chain(scenario.expected().iter())
        .filter_map(|(path, _)| match path {
            ObservationPath::Storage {
                storage: candidate,
                path,
            } if candidate == storage => Some(path.as_ref()),
            _ => None,
        })
        .collect::<BTreeSet<_>>();
    if paths.is_empty() {
        return Err(ScenarioRunError::InvalidDeployment(format!(
            "owned storage {storage} has no declared initial or expected paths to clear"
        )));
    }
    for path in paths {
        server.command(&format!("data remove storage {storage} {path}"))?;
    }
    Ok(())
}

fn setup_owned_resources(
    server: &mut TestServer,
    scenario: &MinecraftScenario,
) -> Result<(), ScenarioRunError> {
    for resource in scenario.owned_resources() {
        match resource {
            OwnedResource::Objective(objective) => {
                server.command(&format!("scoreboard objectives add {objective} dummy"))?;
                server.wait_for_command_log("Created new objective")?;
            }
            OwnedResource::ForcedChunk { dimension, x, z } => {
                let (x, z) = chunk_block_coordinates(*x, *z)?;
                server.command(&format!("execute in {dimension} run forceload add {x} {z}"))?;
            }
            OwnedResource::Storage(_) | OwnedResource::EntityTag(_) => {}
            OwnedResource::Block { .. }
            | OwnedResource::Bossbar(_)
            | OwnedResource::Gamerule(_) => {
                return Err(ScenarioRunError::UnsupportedSurface(format!(
                    "unsupported setup resource {resource:?}"
                )));
            }
        }
    }
    Ok(())
}

fn chunk_block_coordinates(x: i32, z: i32) -> Result<(i32, i32), ScenarioRunError> {
    x.checked_mul(16).zip(z.checked_mul(16)).ok_or_else(|| {
        ScenarioRunError::InvalidDeployment(format!(
            "forced chunk coordinates {x},{z} overflow block coordinates"
        ))
    })
}

fn render_invocation(scenario: &MinecraftScenario, entry: &ResourceLocation) -> String {
    let frame = scenario.invocation();
    let mut modifiers = vec![];
    if let Executor::Entities(selector) = frame.executor() {
        modifiers.push(format!("as {}", selector.as_str()));
    }
    if let Some(dimension) = frame.dimension() {
        modifiers.push(format!("in {dimension}"));
    }
    if let Some(position) = frame.position() {
        let [x, y, z] = position.coordinates().map(format_coordinate);
        modifiers.push(format!("positioned {x} {y} {z}"));
    }
    if let Some(rotation) = frame.rotation() {
        let [yaw, pitch] = rotation.coordinates().map(format_coordinate);
        modifiers.push(format!("rotated {yaw} {pitch}"));
    }
    if let Some(anchor) = frame.anchor() {
        modifiers.push(format!(
            "anchored {}",
            match anchor {
                Anchor::Feet => "feet",
                Anchor::Eyes => "eyes",
            }
        ));
    }
    if modifiers.is_empty() {
        format!("function {entry}")
    } else {
        format!("execute {} run function {entry}", modifiers.join(" "))
    }
}

fn format_coordinate(coordinate: Coordinate) -> String {
    match coordinate {
        Coordinate::Absolute(value) => value.to_string(),
        Coordinate::Relative(0.0) => "~".to_owned(),
        Coordinate::Relative(value) => format!("~{value}"),
        Coordinate::Local(0.0) => "^".to_owned(),
        Coordinate::Local(value) => format!("^{value}"),
    }
}

fn driver_namespace(scenario: &MinecraftScenario) -> String {
    format!("mdl_ps1_{:016x}", scenario.generation().get())
}

fn outcome_storage(scenario: &MinecraftScenario) -> String {
    format!("{}:outcomes", driver_namespace(scenario))
}

fn continuation_holder(policy_index: usize) -> String {
    format!("#continued_{policy_index}")
}

fn completion_marker(scenario: &MinecraftScenario, policy_index: usize) -> String {
    format!(
        "MDL_PS1_DONE_{:016X}_{policy_index}",
        scenario.generation().get()
    )
}

fn write_failure_report(
    root: &Path,
    scenario: &MinecraftScenario,
    error: &ScenarioRunError,
    recent_log: &str,
) {
    let report = format!(
        "{}\n\nerror:\n{}\n\nrecent attributed log:\n{}\n",
        scenario.render(),
        error,
        recent_log
    );
    let _ = fs::write(root.join("scenario-failure.txt"), report);
}

/// Failure to prepare, execute, or compare a semantic scenario.
#[derive(Debug)]
pub enum ScenarioRunError {
    /// Dedicated-server harness failure.
    Harness(HarnessError),
    /// Compiler bridge supplied inconsistent deployment artifacts.
    InvalidDeployment(String),
    /// Scenario uses a typed surface not implemented by this runner tranche.
    UnsupportedSurface(String),
    /// Vanilla command feedback did not match the pinned query protocol.
    QueryParse(String),
    /// One policy disagreed with the explicit semantic expectation.
    ObservationMismatch {
        /// Scenario identity.
        scenario: String,
        /// Failing policy.
        policy: CompilerPolicy,
        /// Bounded state difference.
        comparison: ObservationComparison,
    },
    /// Captured command channels disagree with the explicit expectation.
    OutcomeMismatch {
        /// Scenario identity.
        scenario: String,
        /// Failing policy.
        policy: CompilerPolicy,
        /// Declared channel contract.
        expected: CommandOutcomeExpectation,
        /// Captured channels.
        actual: CommandOutcomeObservation,
    },
    /// A bare exact-limit root disagreed with its terminal measured marker.
    LimitCompletionMismatch {
        /// Scenario identity.
        scenario: String,
        /// Failing policy.
        policy: CompilerPolicy,
        /// Limit being calibrated.
        kind: ExactLimitKind,
        /// Exact gamerule value.
        configured_limit: u32,
        /// Declared root completion.
        expected: bool,
        /// Observed root completion.
        actual: bool,
    },
    /// Two policy products disagreed after normalization.
    PolicyMismatch {
        /// First scenario policy.
        reference: CompilerPolicy,
        /// Differing policy.
        actual: CompilerPolicy,
        /// Bounded state difference.
        comparison: ObservationComparison,
    },
    /// Two policy products published different command channels.
    PolicyOutcomeMismatch {
        /// First scenario policy.
        reference: CompilerPolicy,
        /// Differing policy.
        actual: CompilerPolicy,
        /// First captured outcome.
        reference_outcome: Option<CommandOutcomeObservation>,
        /// Differing captured outcome.
        actual_outcome: Option<CommandOutcomeObservation>,
    },
    /// A failure retained the complete disposable world and installed packs.
    PreservedFailure {
        /// Retained sandbox root.
        sandbox: PathBuf,
        /// Original failure.
        source: Box<Self>,
    },
}

impl fmt::Display for ScenarioRunError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Harness(error) => write!(formatter, "{error}"),
            Self::InvalidDeployment(message) => write!(formatter, "invalid deployment: {message}"),
            Self::UnsupportedSurface(message) => {
                write!(formatter, "unsupported scenario surface: {message}")
            }
            Self::QueryParse(message) => write!(formatter, "query protocol changed: {message}"),
            Self::ObservationMismatch {
                scenario,
                policy,
                comparison,
            } => write!(
                formatter,
                "scenario {scenario} failed under {policy}:\n{comparison}"
            ),
            Self::OutcomeMismatch {
                scenario,
                policy,
                expected,
                actual,
            } => write!(
                formatter,
                "scenario {scenario} command outcome failed under {policy}: expected {expected:?}, actual {actual:?}"
            ),
            Self::LimitCompletionMismatch {
                scenario,
                policy,
                kind,
                configured_limit,
                expected,
                actual,
            } => write!(
                formatter,
                "scenario {scenario} exact {kind:?} limit {configured_limit} completion failed under {policy}: expected {expected}, actual {actual}"
            ),
            Self::PolicyMismatch {
                reference,
                actual,
                comparison,
            } => write!(
                formatter,
                "policy {actual} disagrees with {reference}:\n{comparison}"
            ),
            Self::PolicyOutcomeMismatch {
                reference,
                actual,
                reference_outcome,
                actual_outcome,
            } => write!(
                formatter,
                "policy {actual} outcome {actual_outcome:?} disagrees with {reference} outcome {reference_outcome:?}"
            ),
            Self::PreservedFailure { sandbox, source } => write!(
                formatter,
                "{source}\nfailed scenario sandbox preserved at {}",
                sandbox.display()
            ),
        }
    }
}

impl Error for ScenarioRunError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Harness(error) => Some(error),
            Self::PreservedFailure { source, .. } => Some(source),
            _ => None,
        }
    }
}

impl From<HarnessError> for ScenarioRunError {
    fn from(error: HarnessError) -> Self {
        Self::Harness(error)
    }
}

impl From<super::ObservationSetError> for ScenarioRunError {
    fn from(error: super::ObservationSetError) -> Self {
        Self::InvalidDeployment(error.to_string())
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::{
        CommandOutcomeObservation, DriverCommand, PolicyDeployment, SemanticScenarioCase,
        format_coordinate, install_driver, outcome_matches, parse_nbt_feedback,
        parse_score_feedback, validate_exact_limit_surface, validate_runner_surface,
        validate_semantic_suite,
    };
    use crate::ServerSandbox;
    use crate::scenario::{
        CommandOutcomeExpectation, CompilerPolicy, CompletionExpectation, Coordinate, CorePolicy,
        ExactLimitContract, ExactLimitKind, GenerationNonce, MinecraftPolicy, ObservationPath,
        OutcomeChannelExpectation, OwnedResource, ResourceLocation, ScenarioEntry, ScenarioId,
        ScenarioMode, ScenarioSpec, TestName,
    };

    fn policy() -> CompilerPolicy {
        CompilerPolicy::new(CorePolicy::None, MinecraftPolicy::None)
    }

    fn scenario() -> crate::scenario::MinecraftScenario {
        ScenarioSpec::new(
            ScenarioId::new("runner/scalar").unwrap(),
            GenerationNonce::new(9).unwrap(),
            ScenarioEntry::Export(TestName::new("choose").unwrap()),
        )
        .with_policies(vec![policy()])
        .build()
        .unwrap()
    }

    fn deployment() -> PolicyDeployment {
        PolicyDeployment::new(
            policy(),
            "mdl_policy",
            vec![].into_boxed_slice(),
            ScenarioEntry::Export(TestName::new("choose").unwrap()),
            vec![DriverCommand::new("scoreboard players set #arg mdl.reg 1").unwrap()]
                .into_boxed_slice(),
            ResourceLocation::parse("mdl_policy:entry").unwrap(),
            vec![DriverCommand::new("scoreboard players set #result mdl.case 1").unwrap()]
                .into_boxed_slice(),
        )
    }

    #[test]
    fn score_feedback_parser_is_holder_and_objective_specific() {
        let line = "[Server thread/INFO]: #result has -2147483648 [mdl.case]";
        assert_eq!(
            parse_score_feedback(line, "#result", "mdl.case"),
            Some(i32::MIN)
        );
        assert_eq!(parse_score_feedback(line, "#other", "mdl.case"), None);
        assert_eq!(parse_score_feedback(line, "#result", "wrong"), None);
    }

    #[test]
    fn nbt_feedback_parser_preserves_exact_types_and_rejects_wrong_transport() {
        let line = "[Server thread/INFO]: mdl:test has the following contents: {x:1b,y:[2,3]}";
        assert_eq!(
            parse_nbt_feedback(line).unwrap().to_string(),
            r#"{"x":1b,"y":[2,3]}"#
        );
        assert!(parse_nbt_feedback("not NBT feedback").is_err());
    }

    #[test]
    fn semantic_suite_rejects_empty_and_colliding_cases_before_java() {
        assert!(validate_semantic_suite(&[]).is_err());
        let scenario = scenario();
        let deployments = [deployment()];
        let case = SemanticScenarioCase::new(&scenario, &deployments);
        assert!(validate_semantic_suite(&[case]).is_ok());
        assert!(validate_semantic_suite(&[case, case]).is_err());
    }

    #[test]
    fn coordinate_rendering_preserves_all_three_families() {
        assert_eq!(format_coordinate(Coordinate::Absolute(-2.5)), "-2.5");
        assert_eq!(format_coordinate(Coordinate::Relative(0.0)), "~");
        assert_eq!(format_coordinate(Coordinate::Relative(10.0)), "~10");
        assert_eq!(format_coordinate(Coordinate::Local(0.0)), "^");
    }

    #[test]
    fn runner_rejects_policy_and_logical_entry_mismatches_before_java() {
        let scenario = scenario();
        assert!(validate_runner_surface(&scenario, &[]).is_err());
        let mut wrong = deployment();
        wrong.logical_entry = ScenarioEntry::Export(TestName::new("other").unwrap());
        assert!(
            validate_runner_surface(&scenario, &[wrong])
                .unwrap_err()
                .to_string()
                .contains("scenario requests")
        );
        assert!(validate_runner_surface(&scenario, &[deployment()]).is_ok());
    }

    #[test]
    fn semantic_and_exact_limit_runners_are_structurally_disjoint() {
        let objective = TestName::new("mdl.limit").unwrap();
        let completion = ObservationPath::Score {
            holder: "#completed".into(),
            objective: objective.clone(),
        };
        let exact = ScenarioSpec::new(
            ScenarioId::new("runner/exact").unwrap(),
            GenerationNonce::new(11).unwrap(),
            ScenarioEntry::Export(TestName::new("choose").unwrap()),
        )
        .with_policies(vec![policy()])
        .with_mode(ScenarioMode::ExactLimit(ExactLimitContract::new(
            ExactLimitKind::Sequence,
            10,
            completion,
            false,
        )))
        .with_owned_resources(vec![OwnedResource::Objective(objective)])
        .build()
        .unwrap();

        assert!(validate_runner_surface(&exact, &[deployment()]).is_err());
        assert!(validate_exact_limit_surface(&exact, &[deployment()]).is_ok());
        assert!(validate_exact_limit_surface(&scenario(), &[deployment()]).is_err());
    }

    #[test]
    fn driver_is_fully_materialized_before_server_startup() {
        let scenario = scenario();
        let deployment = deployment();
        let sandbox = ServerSandbox::create(false).unwrap();
        install_driver(&sandbox, &scenario, &[deployment]).unwrap();
        let function = sandbox.root().join(
            "world/datapacks/mdl_ps1_0000000000000009_pack/data/mdl_ps1_0000000000000009/function/policy_0.mcfunction",
        );
        let contents = fs::read_to_string(function).unwrap();
        assert!(!contents.contains("scoreboard players set #arg mdl.reg 1"));
        assert!(contents.contains("function mdl_policy:entry"));
        assert!(contents.contains("scoreboard players set #result mdl.case 1"));
        assert!(contents.contains("scoreboard players set #continued_0 mdl.ps1 1"));
        assert!(
            contents.find("function mdl_policy:entry").unwrap()
                < contents
                    .find("scoreboard players set #continued_0")
                    .unwrap()
        );
        assert!(
            contents
                .find("scoreboard players set #continued_0")
                .unwrap()
                < contents
                    .find("scoreboard players set #result mdl.case 1")
                    .unwrap()
        );
        assert!(!contents.contains("say MDL_PS1_DONE"));
    }

    #[test]
    fn outcome_driver_uses_optional_nbt_channels_without_integer_sentinels() {
        let scenario = ScenarioSpec::new(
            ScenarioId::new("runner/outcome").unwrap(),
            GenerationNonce::new(10).unwrap(),
            ScenarioEntry::Export(TestName::new("choose").unwrap()),
        )
        .with_policies(vec![policy()])
        .with_mode(ScenarioMode::Semantic {
            outcome: Some(CommandOutcomeExpectation::new(
                OutcomeChannelExpectation::Value(true),
                OutcomeChannelExpectation::Value(i32::MIN),
                CompletionExpectation::Continued,
            )),
        })
        .build()
        .unwrap();
        let sandbox = ServerSandbox::create(false).unwrap();
        install_driver(&sandbox, &scenario, &[deployment()]).unwrap();
        let function = sandbox.root().join(
            "world/datapacks/mdl_ps1_000000000000000a_pack/data/mdl_ps1_000000000000000a/function/policy_0.mcfunction",
        );
        let contents = fs::read_to_string(function).unwrap();
        assert!(contents.contains("store success storage"));
        assert!(contents.contains("p0.success byte 1 store result storage"));
        assert!(contents.contains("p0.result int 1 run function mdl_policy:entry"));
        assert!(!contents.contains(&i32::MIN.to_string()));
    }

    #[test]
    fn outcome_expectations_keep_availability_value_and_continuation_separate() {
        let actual = CommandOutcomeObservation {
            success: Some(true),
            result: Some(0),
            continued: true,
        };
        assert!(outcome_matches(
            CommandOutcomeExpectation::new(
                OutcomeChannelExpectation::Value(true),
                OutcomeChannelExpectation::Value(0),
                CompletionExpectation::Continued,
            ),
            actual,
        ));
        assert!(!outcome_matches(
            CommandOutcomeExpectation::new(
                OutcomeChannelExpectation::Unavailable,
                OutcomeChannelExpectation::Value(0),
                CompletionExpectation::Continued,
            ),
            actual,
        ));
        assert!(!outcome_matches(
            CommandOutcomeExpectation::new(
                OutcomeChannelExpectation::Value(true),
                OutcomeChannelExpectation::Value(0),
                CompletionExpectation::Interrupted,
            ),
            actual,
        ));
    }
}
